/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControlPedido;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Milton Rodriguez
 */
public class VentanaPrincipal extends javax.swing.JFrame implements ActionListener{
    private ButtonGroup b = new ButtonGroup();//creo objeto de tipo ButtonGroup y con .add agrego los radiobuttons ahi, para que solo se pueda seleccionar 1 opcion a la vez entre esos radiobuttons.
    private ButtonGroup b2 = new ButtonGroup();//lo mismo para los checkbuttons
    // "b" es el grupo de radiobuttons: cofarma, empsephar y cemefar
    // "b2" es el grupo de checkbuttons: sede norte y sede sur.
    // ambos son objetos de tipo ButtonGroup que sirven para agrupar botones y hacer que solo se pueda seleccionar uno de ellos, como en un formulario normal.

    private DefaultTableModel modelo1 = new DefaultTableModel();//modelo de tabla que contendra todos los pedidos, se le iran agregando a medida que se en el boton "realizar pedido"
    private DefaultTableModel modelo2 = new DefaultTableModel();//modelo de tabla que contendra lo que el usuario haya establecido en el formulario de busqueda
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        
        //agrego los radiobuttons de cofarma, empsephar y cemefar al buttongroup b
        b.add(radiocofarma);
        b.add(radioempsephar);
        b.add(radiocemefar);
        
        //agrego los checkbuttons de sede norte y sede sur al buttongroup b2
        b2.add(checknorte);
        b2.add(checksur);
        
        botonrealizarpedido.addActionListener(this);
        botonborrarformulario.addActionListener(this);
        
        modelo1.addColumn("Medicamento");
        modelo1.addColumn("Tipo");
        modelo1.addColumn("Cantidad");
        modelo1.addColumn("Distribuidor");
        modelo1.addColumn("Sucursal");
        
        modelo2.addColumn("Medicamento");
        modelo2.addColumn("Tipo");
        modelo2.addColumn("Cantidad");
        modelo2.addColumn("Distribuidor");
        modelo2.addColumn("Sucursal");
        
        radiovertodoslospedidos.addActionListener(this);
        botonbuscar.addActionListener(this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblnombremedicamento = new javax.swing.JLabel();
        txtnombremedicamento = new javax.swing.JTextField();
        lbltipomedicamento = new javax.swing.JLabel();
        combotipo = new javax.swing.JComboBox<>();
        lblcantidad = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        lbldistribuidor = new javax.swing.JLabel();
        radiocofarma = new javax.swing.JRadioButton();
        radioempsephar = new javax.swing.JRadioButton();
        radiocemefar = new javax.swing.JRadioButton();
        lblsucursal = new javax.swing.JLabel();
        checknorte = new javax.swing.JCheckBox();
        checksur = new javax.swing.JCheckBox();
        botonrealizarpedido = new javax.swing.JButton();
        botonborrarformulario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnombremedicamento2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        combosucursal = new javax.swing.JComboBox<>();
        botonbuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        radiovertodoslospedidos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SISTEMA DE PEDIDOS");

        jLabel2.setText("Farmacias San Juan");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblnombremedicamento.setText("Nombre medicamento:");

        lbltipomedicamento.setText("Tipo:");

        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analgesico", "Anestesico", "Antibiotico", "Anticolinergico", "Antipiretico" }));

        lblcantidad.setText("Cantidad:");

        lbldistribuidor.setForeground(new java.awt.Color(0, 0, 0));
        lbldistribuidor.setText("Distribuidor");

        radiocofarma.setText("Cofarma");

        radioempsephar.setText("Empsephar");

        radiocemefar.setText("Cemefar");

        lblsucursal.setForeground(new java.awt.Color(0, 0, 0));
        lblsucursal.setText("Sucursal");

        checknorte.setText("Sede norte");

        checksur.setText("Sede sur");

        botonrealizarpedido.setText("Realizar pedido");

        botonborrarformulario.setText("Borrar formulario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(lbldistribuidor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(lblsucursal)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radiocofarma)
                                .addGap(151, 151, 151)
                                .addComponent(radioempsephar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radiocemefar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblnombremedicamento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtnombremedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbltipomedicamento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(165, 165, 165)
                                        .addComponent(checknorte)
                                        .addGap(101, 101, 101)
                                        .addComponent(checksur))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonrealizarpedido)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonborrarformulario)
                                        .addGap(12, 12, 12)))
                                .addGap(22, 22, 22)
                                .addComponent(lblcantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcantidad)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombremedicamento)
                    .addComponent(txtnombremedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltipomedicamento)
                    .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcantidad)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbldistribuidor)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiocofarma)
                    .addComponent(radioempsephar)
                    .addComponent(radiocemefar))
                .addGap(18, 18, 18)
                .addComponent(lblsucursal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checknorte)
                    .addComponent(checksur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonrealizarpedido)
                    .addComponent(botonborrarformulario))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Busqueda");

        jLabel4.setText("Nombre medicamento:");

        jLabel5.setText("Sucursal:");

        combosucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Sede norte", "Sede sur" }));

        botonbuscar.setText("Buscar");
        botonbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonbuscarActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Resultado de la busqueda");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        radiovertodoslospedidos.setText("Ver todos los pedidos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtnombremedicamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel5)))
                                .addGap(18, 18, 18)
                                .addComponent(combosucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(radiovertodoslospedidos))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonbuscar)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnombremedicamento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(combosucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(botonbuscar))
                    .addComponent(radiovertodoslospedidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    public JTextField getTxtnombremedicamento() {
        return txtnombremedicamento;
    }

    public JComboBox<String> getCombotipo() {
        return combotipo;
    }

    public JTextField getTxtcantidad() {
        return txtcantidad;
    }

    public JCheckBox getChecknorte() {
        return checknorte;
    }

    public JCheckBox getChecksur() {
        return checksur;
    }

    public JRadioButton getRadiocemefar() {
        return radiocemefar;
    }

    public JRadioButton getRadiocofarma() {
        return radiocofarma;
    }

    public JRadioButton getRadioempsephar() {
        return radioempsephar;
    }

    public ButtonGroup getB() {
        return b;
    }

    public ButtonGroup getB2() {
        return b2;
    }

    public DefaultTableModel getModelo1() {
        return modelo1;
    }

    public DefaultTableModel getModelo2() {
        return modelo2;
    }

    public JTable getTabla() {
        return tabla;
    }

    public JTextField getTxtnombremedicamento2() {
        return txtnombremedicamento2;
    }

    public JComboBox<String> getCombosucursal() {
        return combosucursal;
    }

    public JButton getBotonbuscar() {
        return botonbuscar;
    }

    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonborrarformulario;
    private javax.swing.JButton botonbuscar;
    private javax.swing.JButton botonrealizarpedido;
    private javax.swing.JCheckBox checknorte;
    private javax.swing.JCheckBox checksur;
    private javax.swing.JComboBox<String> combosucursal;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcantidad;
    private javax.swing.JLabel lbldistribuidor;
    private javax.swing.JLabel lblnombremedicamento;
    private javax.swing.JLabel lblsucursal;
    private javax.swing.JLabel lbltipomedicamento;
    private javax.swing.JRadioButton radiocemefar;
    private javax.swing.JRadioButton radiocofarma;
    private javax.swing.JRadioButton radioempsephar;
    private javax.swing.JRadioButton radiovertodoslospedidos;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtnombremedicamento;
    private javax.swing.JTextField txtnombremedicamento2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getActionCommand().equals("Realizar pedido")){
            ControlPedido c = new ControlPedido();
            c.setVp(this);
            c.realizarPedido();
        }
        if(e.getActionCommand().equals("Borrar formulario")){
            ControlPedido c = new ControlPedido();
            c.setVp(this);
            c.borrarFormulario();
        }
        if(e.getActionCommand().equals("Ver todos los pedidos")){
            
            if(radiovertodoslospedidos.isSelected()){
                ControlPedido c = new ControlPedido();
                c.setVp(this);
                c.setearModelo1enJtable();
            }else{
                ControlPedido c = new ControlPedido();
                c.setVp(this);
                c.setearModelo2enJtable();
            }
            
        }
        if(e.getActionCommand().equals("Buscar")){
            ControlPedido c = new ControlPedido();
            c.setVp(this);
            c.busquedaPedidos();
        }
        
        
    }
    
    public void mostrarMsgErrorCantidad(){
        MsgErrorCantidad m = new MsgErrorCantidad(this,true);
        m.pack(); // Empaqueta el contenido para establecer el tamaño de la ventana
        m.setLocationRelativeTo(null); // Centra el diálogo en la pantalla
        m.setVisible(true);
    }
    
    public void mostrarMsgErrorNombre(){
        MsgErrorNombre m = new MsgErrorNombre(this,true);
        m.pack(); // Empaqueta el contenido para establecer el tamaño de la ventana
        m.setLocationRelativeTo(null); // Centra el diálogo en la pantalla
        m.setVisible(true);
    }
    
    public void mostrarMsgErrorDistribuidor(){
        MsgErrorDistribuidor m = new MsgErrorDistribuidor(this,true);
        m.pack(); // Empaqueta el contenido para establecer el tamaño de la ventana
        m.setLocationRelativeTo(null); // Centra el diálogo en la pantalla
        m.setVisible(true);
    }
    
    public void mostrarMsgErrorSucursal(){
        MsgErrorSucursal m = new MsgErrorSucursal(this,true);
        m.pack(); // Empaqueta el contenido para establecer el tamaño de la ventana
        m.setLocationRelativeTo(null); // Centra el diálogo en la pantalla
        m.setVisible(true);
    }
    
    
    
    
}
